spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=clinica_veterinaria;integratedSecurity=true;encrypt=true;trustServerCertificate=true
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

server.port=8080